switch:
  - platform: phicomm_dc1m
    name: dc1
    hidden: true
    ip: "192.168.2.116"
    ports: {'1':'dc1_s1','2':'dc1_s2','3':'dc1_s3'}
  - platform: phicomm_dc1m
    name: dc1_2
    hidden: true
    ip: "192.168.2.122"
    ports: {'1':'dc1_2_s1','2':'dc1_2_s2','3':'dc1_2_s3'}
  - platform: template
    switches:
      dc1_template:
        friendly_name: 总开关
        value_template: "{{ is_state('switch.dc1', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.dc1
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.dc1
      dc1_s1_template:
        friendly_name: POE设备
        value_template: "{{ is_state('switch.dc1_s1', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.dc1_s1
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.dc1_s1
      dc1_s2_template:
        friendly_name: IP710
        value_template: "{{ is_state('switch.dc1_s2', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.dc1_s2
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.dc1_s2
      dc1_s3_template:
        friendly_name: 外置硬盘
        value_template: "{{ is_state('switch.dc1_s3', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.dc1_s3
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.dc1_s3
sensor:
  - platform: template
    sensors:
      dc1_v:
        friendly_name: 当前电压
        value_template: "{{ states.switch.dc1.attributes.v }}"
        unit_of_measurement: V
      dc1_p:
        friendly_name: 当前功率
        value_template: "{{ states.switch.dc1.attributes.p }}"
        unit_of_measurement: W
      dc1_2_v:
        friendly_name: 当前电压
        value_template: "{{ states.switch.dc1_2.attributes.v }}"
        unit_of_measurement: V
      dc1_2_p:
        friendly_name: 当前功率
        value_template: "{{ states.switch.dc1_2.attributes.p }}"
        unit_of_measurement: W
      # dc1_totale:
      #   friendly_name: 累计用电
      #   value_template: "{{ states.switch.dc1.attributes.totalelect }}"
      #   unit_of_measurement: 度
group:
  dc1:
    name: 工作区DC1排插
    view: no
    entities:
      - sensor.dc1_v
      - sensor.dc1_p
      #- sensor.dc1_totale
      - switch.dc1_template
      - switch.dc1_s1_template
      - switch.dc1_s2_template
      - switch.dc1_s3_template
  dc1_2:
    name: DC1排插2
    view: no
    entities:
      - sensor.dc1_2_v
      - sensor.dc1_2_p
      #- sensor.dc1_totale
      - switch.dc1_2
      - switch.dc1_2_s1
      - switch.dc1_2_s2
      - switch.dc1_2_s3
homeassistant:        
  customize:
    # Add an entry for each entity that you want to overwrite.
    switch.dc1:
      hidden: true
    switch.dc1_s1:
      hidden: true
    switch.dc1_s2:
      hidden: true
    switch.dc1_s3:
      hidden: true
